# Folder where the data is stored
results_folder: ~/HydroNODE_fork/M100_results_569basins_1980_2010_BS3_julia_150ep_lr4
# results_folder: ~/HydroNODE_fork/M100_results_569basins_1980_2010_BS3_julia_300ep_lr4

# Folder (to be created) where the processed data will be stored
plots_folder: plots_hybrid_mlp32x5_7304b_BS3_julia_150ep
# plots_folder: plots_hybrid_mlp32x5_7304b_BS3_julia_300ep

graph_title:  Hybrid model (exp-hydro) - MLP/BS3

# Periods to be processed
periods:
  - train
  - test

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less