basin_file: 4_basin_file.txt
basin_file_path: 4_basin_file.txt
concept_data_dir: /gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_US
concept_inputs:
- prcp
- dayl
- tmean
- tmin
- tmax
- srad
- vp
concept_model: exphydro
concept_target:
- obs_runoff
config_dir: .
dataset: camelsus
device: cpu
experiment_name: run_concept_model
forcings:
- daymet
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r
number_of_basins: 4
ode_solver_lib: scipy
odesmethod: euler
periods:
- train
- valid
plots_dir: runs/run_concept_model_241125_200307/model_plots
precision: float32
results_dir: runs/run_concept_model_241125_200307/model_results
run_dir: runs/run_concept_model_241125_200307
seed: 111
time_step: 0.5
train_end_date: 30/09/2000
train_start_date: 01/10/1980
valid_end_date: 30/09/2010
valid_start_date: 01/10/2000
verbose: 1
