# --- Data configurations --- #
# Dataset to use for training and testing [camelsus, summaca]
dataset: camelsus
# concept_data_dir: ../../../../../gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_US
## See file src/utils/data_dir.yml for more details
concept_data_dir: data_dir_camelsus

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended, nldas_hourly]
forcings: 
  - daymet

# Files to specify training, validation and test basins
# basin_file: 569_basin_file.txt
basin_file: 4_basin_file.txt

# --- Model configurations --- #
# Conceptual model to use [exphydro, ...
# exphydro model: Two buckets (water and snow), 5 processes and 6 parameters
# Ref: exphydro -> https://hess.copernicus.org/articles/26/5085/2022/
concept_model: exphydro

ode_solver_lib: scipy
# Method to solve the ODEs (using solve_ivp from scipy.integrate)
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html
# Options: RK45, RK23, DOP853, Radau, BDF, LSODA
# odesmethod: Radau
# rtol: 1e-4
# atol: 1e-6
# odesmethod: rk4
# time_step: 0.1
odesmethod: euler
time_step: 1.0


# ode_solver_lib: torchdiffeq
# # Method to solve the ODEs with torchdiffeq [bosh3, rk4, dopri5, euler, adaptive_heun, midpoint]
# # https://github.com/rtqichen/torchdiffeq/blob/master/README.md
# # odesmethod: bosh3
# # rtol: 1e-4
# # atol: 1e-6

# odesmethod: dopri5
# rtol: 1e-6
# atol: 1e-9

# # # odesmethod: rk4
# # # time_step: 1.0
# # # odesmethod: scipy_solver
# # # scipy_solver: RK23

# # odesmethod: euler
# # time_step: 0.05

# --- Training configurations --- #
# Period to train, validate and test the model (they should be consecutive)
# train_start_date: "01/10/1980"
# train_end_date: "30/09/2000"
# valid_start_date: "01/10/2000"
# valid_end_date: "30/09/2010"

train_start_date: "01/10/1995"
train_end_date: "30/09/2000"
valid_start_date: "01/10/2000"
valid_end_date: "30/09/2005"

# Metrics to use for evaluation
metrics:
  - NSE
  - Alpha-NSE
  - Beta-NSE
  - FHV
  - FMS
  - FLV
  - KGE
  - Beta-KGE
  - Peak-Timing
  - Peak-MAPE
  - Pearson-r

## --- Run configurations --- ##
# Experiment name, used as folder name
# experiment_name: M0_results_569basins_1980_2010_RK4
# experiment_name: M0_results_569basins_1980_2010_RK23_tol33
# experiment_name: M0_results_569basins_1980_2010_LSODA_tol36
# experiment_name: M0_results_569basins_1980_2010_RK45_tol36

# experiment_name: __M0_results_4basins_1980_2010_RK23_tol46_scipy
# experiment_name: __M0_results_4basins_1980_2010_bosh3tol33_torchdiffeq
# experiment_name: __M0_results_4basins_1980_2010_bosh3tol46_torchdiffeq
# experiment_name: __M0_results_4basins_1980_2010_euler01d_torchdiffeq
# experiment_name: __M0_results_4basins_1980_2010_rk4_1d_torchdiffeq
# experiment_name: __M0_results_4basins_1980_2010_rk4_01d_torchdiffeq
# experiment_name: __M0_results_4basins_1980_2010_RK23tol46scipy_torchdiffeq

# experiment_name: _______________M0_results_4basins_test

# experiment_name: M0_results_569basins_1980_2010_euler005d_torchdiffeq
# experiment_name: ____M0_results_569basins_1980_2010_rk4_1d_torchdiffeq
# experiment_name: ____M0_results_569basins_1980_2010_RK23_tol33_torchdiffeq
# experiment_name: ____M0_results_569basins_1980_2010_RK45_tol69_torchdiffeq
# experiment_name: ____M0_results_569basins_1980_2010_RK23_tol46_scipy
# experiment_name: __M0_results_4basins_1980_2010_RK23_tol33_7vars
# experiment_name: M0_results_569basins_1980_2010_RK23_tol33_7vars
# experiment_name: M0_results_569basins_1980_2010_RK23_tol33_7vars
# experiment_name: M0_results_569basins_1980_2010_RK45_tol46_7vars
# experiment_name: M0_results_569basins_1980_2010_RK45_tol69_7vars
# experiment_name: M0_results_569basins_1980_2010_RK45_tol912_7vars
# experiment_name: M0_results_569basins_1980_2010_DOP853_tol69_7vars
# experiment_name: M0_results_569basins_1980_2010_Radau_tol46_7vars
# experiment_name: M0_results_569basins_1980_2010_bosh3_tol33_torchdiffeq
# experiment_name: M0_results_569basins_1980_2010_bosh3_tol46_torchdiffeq
# experiment_name: M0_results_569basins_1980_2010_dopr5_tol69_torchdiffeq
# experiment_name: M0_results_569basins_1980_2010_euler1d_custom
# experiment_name: M0_results_569basins_1980_2010_euler05d_custom
# experiment_name: M0_results_569basins_1980_2010_euler01d_custom
# experiment_name: M0_results_569basins_1980_2010_euler005d_custom
# experiment_name: M0_results_569basins_1980_2010_euler001d_custom
# experiment_name: M0_results_569basins_1980_2010_rk4_1d_custom
# experiment_name: M0_results_569basins_1980_2010_rk4_05d_custom
# experiment_name: ____M0_results_4basins_1980_2010_euler1d_custom
# experiment_name: ____M0_results_4basins_1980_2010_euler05d_custom
experiment_name: _____________M0_results_4basins_1980_2010_euler01d_custom
# experiment_name: ____M0_results_4basins_1980_2010_euler005d_custom
# experiment_name: ____M0_results_4basins_1980_2010_rk4_1d_custom
# experiment_name: ____M0_results_4basins_1980_2010_rk4_01d_custom



# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cpu

# Set seed for reproducibility
seed: 111

# Set precision for the model [float32, float64]
precision: float32

# Verbose level [0, 1] (0: only log info messages, don't show progress bars, 1: show progress bars)
verbose: 1