# --- Data configurations --- #
# Dataset to use for training and testing [camelsus, summaca]
dataset: camelsus
data_dir: ../../../../../gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_US

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended, nldas_hourly]
forcings: 
  - daymet

# nn_dynamic_inputs:
#   - prcp(mm/day)
#   - dayl(s)
#   - tmean(C)

# target_variables: 
#   - obs_runoff(mm/day)

# Files to specify training, validation and test basins
# basin_file: 25_basin_file.txt
basin_file: 2_basin_file.txt
# basin_file: 569_basin_file.txt

# --- Model configurations --- #
# Conceptual model to use [exphydro, ...
# Ref: exphydro -> https://hess.copernicus.org/articles/26/5085/2022/
concept_model: exphydro

# --- Training configurations --- #
# Period to train, validate and test the model (they should be consecutive)
train_start_date: "01/10/1980"
train_end_date: "30/09/2000"
valid_start_date: "01/10/2000"
valid_end_date: "30/09/2010"
# test_start_date: "01/10/2000"
# test_end_date: "30/09/2010"

# Metrics to use for evaluation
metrics:
  - NSE
  - Alpha-NSE
  - Beta-NSE
  - FHV
  - FMS
  - FLV
  - KGE
  - Beta-KGE
  - Peak-Timing
  - Peak-MAPE
  - Pearson-r

## --- Run configurations --- ##
# Experiment name, used as folder name
experiment_name: concept_run

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# Set seed for reproducibility
seed: 1111

# Set precision for the model [float32, float64]
precision: float32

# Verbose level [0, 1] (0: only log info messages, don't show progress bars, 1: show progress bars)
verbose: 1