# Folder where the data is stored
results_folder: ~/HydroNODE_fork/M0_results_569basins_1980_2010_BS3_julia
# results_folder: ~/HydroNODE_fork/M0_results_569basins_1980_2010_BS3tol69_julia
# results_folder: ~/HydroNODE_fork/M0_results_569basins_1980_2010_DP5tol33_julia
# results_folder: ~/HydroNODE_fork/M0_results_569basins_1980_2010_DP5tol912_julia

# Folder (to be created) where the processed data will be stored
plots_folder: plots_conceptualBS3_julia
# plots_folder: plots_conceptualBS3tol69_julia
# plots_folder: plots_conceptualDP5tol33_julia
# plots_folder: plots_conceptualDP5tol912_julia

graph_title: Conceptual model (exp-hydro) - BOSH3
# graph_title: Conceptual model (exp-hydro) - BOSH3tol69
# graph_title: Conceptual model (exp-hydro) - DP5tol33
# graph_title: Conceptual model (exp-hydro) - DP5tol912

# Periods to be processed
periods:
  - train
  - test

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less