# # Folder where the data is stored
# results_folder: ../../data/M0_results_569basins_1980_2010_RK23
# # results_folder: ../../data/M0_results_569basins_1980_2010_RK23_tol36_240815_071129
# # results_folder: ../../data/M0_results_569basins_1980_2010_LSODA_tol36_240815_071831
# # results_folder: ../../examples/runs/M0_results_569basins_1980_2010_RK45_tol36_240816_140420
# # results_folder: ../../examples/runs/M0_results_569basins_1980_2010_RK4_240816_165349
# # results_folder: ../../examples/runs/M0_results_569basins_1980_2010_RK23_tol33_240816_165631
# # results_folder: ../../examples/runs/M0_results_569basins_1980_2010_RK23_tol39_240816_153209

# # Folder (to be created) where the processed data will be stored
# plots_folder: plots_conceptualRK23
# # plots_folder: plots_conceptualRK23_tol39
# # plots_folder: plots_conceptualRK23_tol36
# # plots_folder: plots_conceptualRK4

# graph_title: Conceptual model (exp-hydro) - RK23
# # graph_title: Conceptual model (exp-hydro) - RK23_tol39
# # graph_title: Conceptual model (exp-hydro) - LSODA_tol36
# # graph_title: Conceptual model (exp-hydro) - RK45_tol36
# # graph_title: Conceptual model (exp-hydro) - RK4


# results_folder: ../../../data/M0_results_569basins_1980_2010_RK23
# plots_folder: plots_conceptualRK23
# graph_title: Conceptual model (exp-hydro) - RK23tol33


# results_folder: ../../../data/M0_results_569basins_1980_2010_RK23_tol33_7vars
# plots_folder: plots_conceptualRK23_tol33_7vars
# graph_title: Conceptual model (exp-hydro) - RK23_tol33

# results_folder: ../../../data/M0_results_569basins_1980_2010_RK23_tol46_7vars
# plots_folder: plots_conceptualRK23_tol46_7vars
# graph_title: Conceptual model (exp-hydro) - RK23_tol46

# results_folder: ../../../data/M0_results_569basins_1980_2010_RK45_tol46_7vars
# plots_folder: plots_conceptualRK45_tol46_7vars
# graph_title: Conceptual model (exp-hydro) - RK45_tol46

# results_folder: ../../../data/M0_results_569basins_1980_2010_RK45_tol69_7vars
# plots_folder: plots_conceptualRK45_tol69_7vars
# graph_title: Conceptual model (exp-hydro) - RK45_tol69

# results_folder: ../../../data/M0_results_569basins_1980_2010_DOP853_tol69_7vars
# plots_folder: plots_conceptualDOP853_tol69_7vars
# graph_title: Conceptual model (exp-hydro) - DOP853_tol69


# results_folder: ../../../data/M0_results_569basins_1980_2010_RK23_tol46_scipy
# plots_folder: plots_conceptualRK23_tol46_scipy
# graph_title: Conceptual model (exp-hydro) - RK23_tol46_scipy

# results_folder: ../../../data/M0_results_569basins_1980_2010_rk4_1d_torchdiffeq
# plots_folder: plots_conceptualRK4_1d_torchdiffeq
# graph_title: Conceptual model (exp-hydro) - RK4_1d_torchdiffeq

# results_folder: ../../../data/M0_results_569basins_1980_2010_LSODA_tol36_240815_071831
# plots_folder: plots_conceptualLSODA_tol36_scipy
# graph_title: Conceptual model (exp-hydro) - LSODA_tol36

# results_folder: ../../../data/M0_results_569basins_1980_2010_RK45
# plots_folder: plots_conceptualRK45tol36_scipy
# graph_title: Conceptual model (exp-hydro) - RK45_tol36_scipy

# results_folder: ../../../data/M0_results_569basins_1980_2010_euler01d_torchdiffeq
# plots_folder: plots_conceptualEuler01d_torchdiffeq
# graph_title: Conceptual model (exp-hydro) - Euler01d_torchdiffeq

# results_folder: ../../../data/M0_results_569basins_1980_2010_rk4_1d_torchdiffeq
# plots_folder: plots_conceptualRK4_1d_torchdiffeq
# graph_title: Conceptual model (exp-hydro) - RK4_1d_torchdiffeq



# results_folder: ../../../data/M0_results_569basins_1980_2010_rk4_1d_custom
# plots_folder: plots_conceptualRK4_1d_custom
# graph_title: Conceptual model (exp-hydro) - RK4_1d_custom

# results_folder: ../../../data/M0_results_569basins_1980_2010_rk4_05d_custom
# plots_folder: plots_conceptualRK4_05d_custom
# graph_title: Conceptual model (exp-hydro) - RK4_05d_custom

# results_folder: ../../../data/M0_results_569basins_1980_2010_euler1d_custom
# plots_folder: plots_conceptualEuler1d_custom
# graph_title: Conceptual model (exp-hydro) - Euler1d_custom

# results_folder: ../../../data/M0_results_569basins_1980_2010_euler05d_custom
# plots_folder: plots_conceptualEuler05d_custom
# graph_title: Conceptual model (exp-hydro) - Euler05d_custom

# results_folder: ../../../data/M0_results_569basins_1980_2010_euler01d_custom
# plots_folder: plots_conceptualEuler01d_custom
# graph_title: Conceptual model (exp-hydro) - Euler01d_custom

# results_folder: ../../../data/M0_results_569basins_1980_2010_euler005d_custom
# plots_folder: plots_conceptualEuler005d_custom
# graph_title: Conceptual model (exp-hydro) - Euler005d_custom

results_folder: ../../../data/M0_results_569basins_1980_2010_euler001d_custom
plots_folder: plots_conceptualEuler001d_custom
graph_title: Conceptual model (exp-hydro) - Euler001d_custom








# Periods to be processed
periods:
  - train
  - valid

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less