folders4cdf_dir:
  - directory: ../../../data/M0_results_569basins_1980_2010_RK23_tol33_7vars
    experiment: 'RK23 | rtol=1e-3, atol=1e-3 | scipy'
    color: 'tab:red'
    marker: o
    linestyle: '-.'
  - directory: ../../../data/M0_results_569basins_1980_2010_RK23_tol46_7vars
    experiment: 'RK23 | rtol=1e-4, atol=1e-6 | scipy'
    color: 'tab:blue'
    marker: null
    linestyle: '-.'
  - directory: ../../../data/M0_results_569basins_1980_2010_LSODA_tol36
    experiment: 'LSODA | rtol=1e-3, atol=1e-6 | scipy'
    color: 'tab:orange'
    marker: null
    linestyle: '-.'
  - directory: ../../../data/M0_results_569basins_1980_2010_RK45_tol46_7vars
    experiment: 'RK45 | rtol=1e-4, atol=1e-6 | scipy'
    color: 'tab:purple'
    marker: null
    linestyle: '-.'
  - directory: ../../../data/M0_results_569basins_1980_2010_RK45_tol69_7vars
    experiment: 'RK45 | rtol=1e-6, atol=1e-9 | scipy'
    color: 'tab:green'
    marker: null
    linestyle: '-.'
  - directory: ../../../data/M0_results_569basins_1980_2010_DOP853_tol69_7vars
    experiment: 'DOP853 | rtol=1e-6, atol=1e-9 | scipy'
    color: 'tab:brown'
    marker: null
    linestyle: '-.'
  - directory: ../../../data/M0_results_569basins_1980_2010_euler1d_torchdiffeq
    experiment: 'Euler | dt=1d | torchdiffeq'
    color: 'tab:cyan'
    marker: null
    linestyle: ':'
  - directory: ../../../data/M0_results_569basins_1980_2010_euler01d_torchdiffeq
    experiment: 'Euler | dt=0.1d | torchdiffeq'
    color: 'tab:olive'
    marker: null
    linestyle: ':'
  - directory: ../../../data/M0_results_569basins_1980_2010_rk4_1d_torchdiffeq
    experiment: 'RK4 | dt=1d | torchdiffeq'
    color: 'tab:pink'
    marker: null
    linestyle: ':'
  - directory: ../../../data/M0_results_569basins_1980_2010_euler1d_custom
    experiment: 'Euler | dt=1d | custom'
    color: 'olive'
    marker: null
    linestyle: '--'
  - directory: ../../../data/M0_results_569basins_1980_2010_rk4_1d_custom
    experiment: 'RK4 | dt=1d | custom'
    color: 'pink'
    marker: null
    linestyle: '--'