folders4cdf_dir:
  # - directory: ../../scripts_paper/M100_results_569basins_1980_2010_BS3_julia_150ep_lr4
  #   experiment: '$\mathbf{RK23}$ | batch size 7305 | 150 epochs | Julia'
  #   color: 'tab:red'
  # - directory: .../../scripts_paper/569basins_single_mlp32x5_256b_euler1d_lr4_150ep_1000pre_lr3
  #   experiment: Euler1.0d | batch size 256 | 150 epochs'
  #   color: 'tab:blue'
  # - directory: ../../scripts_paper/569basins_single_mlp32x5_7305b_euler01d_lr4_100ep_1000pre_lr3
  #   experiment: 'Euler0.1d | batch size 7305 | 100 epochs'
  #   color: 'tab:green'

  - directory: ../../scripts_paper/M100_results_569basins_1980_2010_BS3_julia_150ep_lr4
    experiment: '$\mathbf{RK23}$ | batch size 7305 | 150 epochs | Julia'
    color: 'tab:red'
  - directory: ../../scripts_paper/569basins_single_mlp32x5_256b_euler05d_lr4_150ep_1000pre_lr3
    experiment: 'Euler0.5d | batch size 256 | 150 epochs'
    color: 'tab:blue'
  - directory: ../../scripts_paper/AAruns_hybrid_single_lstm270d_128h_256b_euler_lr4_100ep
    experiment: 'Euler1.0d | LSTM | batch size 256 | 100 epochs'
    color: 'tab:green'

# Periods to be processed
periods:
  - train
  - valid

