# # Folder where the data is stored
# results_folder: ../../data/M0_results_569basins_1980_2010_RK23

# # Folder (to be created) where the processed data will be stored
# plots_folder: plots_conceptualRK23

# graph_title: Conceptual model (exp-hydro) - RK23

results_folder: ../../../data/M0_results_569basins_1980_2010_RK23
plots_folder: plots_conceptualRK23_tol33
graph_title: Conceptual model (exp-hydro) - RK23_tol33


# Periods to be processed
periods:
  - train
  - valid

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less