# --- Data configurations --- #
# Dataset to use for training and testing [camelsus, summaca]
dataset: camelsus
concept_data_dir: data_dir_camelsus

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended, nldas_hourly]
forcings: 
  - daymet

# Files to specify training, validation and test basins
basin_file: 4_basin_file.txt

# --- Model configurations --- #
concept_model: exphydro

# --- ODE Solver configurations --- #
ode_solver_lib: scipy
odesmethod: euler
time_step: 0.5

# --- Training configurations --- #
train_start_date: "01/10/1980"
train_end_date: "30/09/2000"
valid_start_date: "01/10/2000"
valid_end_date: "30/09/2010"

# Metrics to use for evaluation
metrics:
  - NSE
  - Alpha-NSE
  - Beta-NSE
  - FHV
  - FMS
  - FLV
  - KGE
  - Beta-KGE
  - Peak-Timing
  - Peak-MAPE
  - Pearson-r

## --- Run configurations --- ##
experiment_name: run_concept_model

device: cpu

# Set seed for reproducibility
seed: 111

# Set precision for the model [float32, float64]
precision: float32

# Verbose level [0, 1] (0: only log info messages, don't show progress bars, 1: show progress bars)
verbose: 1