# --- Model configurations --- #
# Conceptual model to use [exphydro, ...
# Ref: exphydro -> https://hess.copernicus.org/articles/26/5085/2022/
concept_model: exphydro

# --- Data configurations --- #
# Folder in src/data containing the outputs from the conceptual model
data_dir: M0_results_569basins_1980_2010_RK23_tol33_7vars

# -- Configurations for the neural network model -- #
nn_model: mlp

nn_dynamic_inputs:
  - s_snow
  - s_water
  - prcp
  - tmean

nn_mech_targets:
  - ps_bucket
  - pr_bucket
  - m_bucket
  - et_bucket
  - q_bucket

target_variables: 
  - obs_runoff

scale_target_vars: True

basin_file: 4_basin_file.txt

# --- Training configurations --- #
# Period to train, validate and test the model (they should be consecutive)
train_start_date: "01/10/1980"
train_end_date: "30/09/2000"
valid_start_date: "01/10/2000"
valid_end_date: "30/09/2010"

# Loss function to use [mse, nse, nse-nh]
loss: mse

# Number of epochs to train the model
epochs_pretrain: 50

# Patience for early stopping
patience: 30

batch_size: 256

# Optimizer to use [adam, sgd]
optimizer: adam

# # Learning rate for the optimizer
learning_rate: 0.01

# Hidden layers for the NN model
hidden_size: 
  - 32
  - 32
  - 32
  - 32
  - 32

## --- Run configurations --- ##
experiment_name: run_pretrain_nn_model

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cpu

# Set seed for reproducibility
seed: 1111

# Set precision for the model [float32, float64]
precision: float32

# Number of parallel workers used in the data pipeline
num_workers: 16

# Verbose level [0, 1] (0: only log info messages, don't show progress bars, 1: show progress bars)
verbose: 1

# If a value and greater than 0, logs n random basins as figures after pretraining the NN model
# If list of basins, logs the specified basins: format is either '01013500' or 1013500
log_n_basins: 4

# If a value and greater than 0, logs figures and metrics, and save model after each n epochs
log_every_n_epochs: 50

# Metrics to use for evaluation (after training)
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r