main_folder: cluster_sample_jobs_59basins
# main_folder: .

run_folders:
  ## Folder name: label
  AA_bash_runs_finetune_mlp_euler1d_240928_100636: "Euler 1d"
  AA_bash_runs_finetune_mlp_euler1d_32x3_240928_101122: "Euler 1d 32x3"

  AA_bash_runs_finetune_mlp_euler05d_240928_100946: "Euler 0.5d"
  AA_bash_runs_finetune_mlp_euler05d_32x3_240928_101408: "Euler 0.5d 32x3"
  AA_bash_runs_finetune_mlp_euler05d_carryover_240924_182518: "Euler 0.5d carryover"
  bash_runs_finetune_fract01_mlp_euler05d_32x3_m0rk4_1d_241010_123935: "Euler 0.5d 32x3 m0rk4 1d"
  AA_bash_runs_finetune_mlp_euler02d_240928_101516: "Euler 0.2d"
  AA_bash_runs_finetune_mlp_euler02d_32x3_240928_101614: "Euler 0.2d 32x3"
  AA_bash_runs_finetune_mlp_midpoint1d_240925_094054: "Midpoint 1d"
  AA_bash_runs_finetune_mlp_midpoint05d_240925_093914: "Midpoint 0.5d"
  AA_bash_runs_finetune_mlp_rk4_1d_240928_101650: "RK4 1d"
  AA_bash_runs_finetune_mlp_rk4_1d_32x3_240928_101801: "RK4 1d 32x3"
  AA_bash_runs_finetune_mlp_rk4_05d_240928_101826: "RK4 0.5d"
  AA_bash_runs_finetune_mlp_rk4_05d_32x3_240928_101926: "RK4 0.5d 32x3"
  AA_bash_runs_finetune_mlp_rk23tol33_240928_102024: "RK23 tol33"
  AA_bash_runs_finetune_mlp_rk23tol33_32x3_240928_102144: "RK23 tol33 32x3"
  AA_bash_runs_finetune_mlp_rk23tol46_240923_080804: "RK23 tol46"
  AA_bash_runs_finetune_mlp_rk23tol46_32x3_240928_102210: "RK23 tol46 32x3"

  # AA_bash_runs_finetune_mlp_rk23tol69_240922_084609: "RK23 tol69"
  # AA_bash_runs_finetune_mlp_rk23tol69_240923_080852: "RK23 tol69 v2"


periods:
  - train
  - valid

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Top models criteria: median, mean, mean_median_score
top_models_criteria: median

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less