main_folder: cluster_sample_jobs_116basins

run_folders:
  ## Folder name: label
  A_bash_runs_finetune_fract02_mlp_euler1d_240919_102943: "Euler 1d"
  A_bash_runs_finetune_fract02_mlp_euler05d_240919_203318: "Euler 0.5d"
  A_bash_runs_finetune_fract02_mlp_euler02d_240921_101931: "Euler 0.2d"
  A_bash_runs_finetune_fract02_mlp_rk4_1d_240923_134138: "RK4 1d"
  A_bash_runs_finetune_fract02_mlp_rk4_05d_240921_113223: "RK4 0.5d"
  A_bash_runs_finetune_fract02_mlp_rk23tol33_240921_152119: "RK23 tol33"
  A_bash_runs_finetune_fract02_mlp_rk23tol46_240923_080920: "RK23 tol46"

periods:
  - train
  - valid

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Top models criteria: median, mean, mean_median_score
top_models_criteria: median

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less