main_folder: .

run_folders:
  ## Folder name: label
  bash_mlp_mlp_euler05d_finetune_240924_113218: "Euler 0.5d"

periods:
  - train
  - valid

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Top models criteria: median, mean, mean_median_score
top_models_criteria: median

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less