main_folder: cluster_sample_jobs_59basins_seeds_euler1d

run_folders:
  ## Folder name: label
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr3_241005_080827: "Euler_1d_32x3_lr3_4inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr4_241004_174411: "Euler_1d_32x3_lr4_4inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr4_300ep_241005_081628: "Euler_1d_32x3_lr4_4inp_300ep"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr34_241004_175042: "Euler_1d_32x3_lr34_4inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr34_100ep_241007_125400: "Euler_1d_32x3_lr34_4inp_100ep"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr45_241006_170303: "Euler_1d_32x3_lr45_4inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr4_5inpA_241004_210250: "Euler_1d_32x3_lr4_5inpA"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr34_5inpA_241004_210839: "Euler_1d_32x3_lr34_5inpA"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr4_5inpB_241004_210345: "Euler_1d_32x3_lr4_5inpB"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr34_5inpA_241005_010208: "Euler_1d_32x3_lr34_5inpB"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr4_6inpA_241004_180832: "Euler_1d_32x3_lr4_6inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr34_6inpA_241004_180917: "Euler_1d_32x3_lr34_6inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr4_7inp_241004_181203: "Euler_1d_32x3_lr4_7inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr34_7inp_241004_181243: "Euler_1d_32x3_lr34_7inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr4_8inp_241004_181331: "Euler_1d_32x3_lr4_8inp"
  bash_runs_finetune_fract01_mlp_euler1d_seeds_32x3_lr34_8inp_241004_181401: "Euler_1d_32x3_lr34_8inp"
  bash_runs_finetune_fract01_mlp_euler05d_seeds_32x3_lr34_100ep_241021_093219: "Euler_05d_32x3_lr34_100ep_carryover"
  bash_runs_finetune_fract01_mlp_euler05d_seeds_32x4_lr34_100ep_241021_093717: "Euler_05d_32x4_lr34_100ep_carryover"
  bash_runs_finetune_fract01_mlp_euler05d_seeds_32x5_lr34_100ep_241021_134635: "Euler_05d_32x5_lr34_100ep_carryover"
  bash_runs_finetune_fract02_mlp_euler05d_seeds_32x5_lr34_100ep_241022_075806: "Euler_05d_32x5_lr34_100ep_carryover_fract02"


periods:
  - train
  - valid

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Top models criteria: median, mean, mean_median_score
top_models_criteria: median

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less