run_folders:
  - AA_bash_runs_finetune_mlp_euler1d_240917_205323
  - AA_bash_runs_finetune_mlp_euler05d_240917_205505
  - AA_bash_runs_finetune_mlp_rk4_240918_020503
  - AA_bash_runs_finetune_mlp_rk23tol33_240918_074306

periods:
  - train
  - valid

# Metrics to be plotted
metrics:
  - nse
  # - fhv
  # - kge

# Thresholds for the metrics
threshold_dict:
  # metric:
  #   - value # Threshold value
  #   - type  # Threshold type, greater or less (greater means that the metric should be greater than the threshold)
  nse : 
    - 0.0         # Threshold value
    - greater     # Threshold type (greater means that the metric should be greater than the threshold)
  kge: 
    - 0.0
    - greater
  fhv:
    - 500
    - less